name: Beta Tester
description: Richiesta accesso anticipato al Viewer gOWLsystem
title: "[Beta Tester] "
labels: ["beta-tester", "viewer"]
body:
  - type: input
    id: email
    attributes:
      label: Email di contatto
      placeholder: nome@studio.it
    validations:
      required: true
  - type: dropdown
    id: professione
    attributes:
      label: Professione
      options:
        - Agronomo / Consulente
        - Tecnico GIS / Telerilevamento
        - Viticoltore / Imprenditore Agricolo
        - Altro
    validations:
      required: true
  - type: textarea
    id: motivazione
    attributes:
      label: Nota motivazionale
      description: Facoltativo
  - type: textarea
    id: aspettative
    attributes:
      label: Feedback / Aspettative
      description: Facoltativo
